test-web:
  needs: [build-web, build-api]
  runs-on: ubuntu-24.04
  steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "pnpm"

    - run: pnpm install

    - name: Create web/.env
      run: |
        echo "NUXT_API_BASE_URL=http://localhost:3001" > web/.env
        echo "NUXT_PORT=3000" >> web/.env
        echo "NUXT_NODE_ENV=development" >> web/.env

    - name: Create api/.env
      run: cp ./api/.test.env ./api/.env

    - run: docker compose up -d --build

    - name: Run schema:change in api container
      run: docker exec api pnpm schema:change

    - run: pnpm --filter web exec cypress install

    - run: pnpm --filter web exec cypress run

    - name: Upload Cypress screenshots on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-screenshots
        path: web/cypress/screenshots

    - name: Show Docker logs
      if: always()
      run: docker compose logs --no-color

    - if: always()
      run: docker compose down
