services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_BASE_URL=http://localhost:3001

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
