site_name: Construx

nav:
  - Architecture:
      - "00 Overview": architecture/index.md
      - "01. Introduction and Goals": architecture/01_introduction_and_goals.md
      - "02. Architecture Constraints": architecture/02_architecture_constraints.md
      - "03. Context and Scope": architecture/03_context_and_scope.md
      - "04. Solution Strategy": architecture/04_solution_strategy.md
      - "05. Building Block View": architecture/05_building_block_view.md
      - "06. Runtime View": architecture/06_runtime_view.md
      - "07. Deployment View": architecture/07_deployment_view.md
      - "08. Concepts": architecture/08_concepts.md
      - "09. Architecture Decisions": architecture/09_architecture_decisions.md
      - "10. Quality Requirements": architecture/10_quality_requirements.md
      - "11. Technical Risks": architecture/11_technical_risks.md
      - "12. Glossary": architecture/12_glossary.md
      - ADRs:
          - "ADR 1: Architecture Style": architecture/adrs/adr-1-architecture-style.md
          - "ADR 2: Technology Stack": architecture/adrs/adr-2-technology-stack.md
          - "ADR 3: Authentication": architecture/adrs/adr-3-authentication.md
          - "ADR 4: ORM and DB": architecture/adrs/adr-4-orm-and-db.md
          - "ADR 5: Email": architecture/adrs/adr-5-email.md

theme:
  name: readthedocs
