name: Test API

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm --filter=api prisma:generate

      - name: Run API tests
        env:
          NODE_ENV: development
          PORT: 3001
          DATABASE_URL: postgresql://user:password@db:5432/mydb
          JWT_SECRET: your-very-secret-string-here
          MAILGUN_API_KEY: some-key
          MAILGUN_DOMAIN: some-domain
          DEFAULT_RECEIVER_EMAIL: your-email
          USE_DEFAULT_EMAIL_RECEIVER: true
          SKIP_EMAIL_SENDING: true
        run: pnpm --filter=api run test
