name: Monorepo CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Type Check all packages
        run: pnpm -r run typecheck --if-present

      - name: Lint all packages
        run: pnpm -r run lint --if-present

      - name: Build all packages
        run: pnpm -r run build --if-present

      - name: Run tests
        run: pnpm -r run test --if-present
